[project]
name = "init-minimal-single"
version = "0.1.0"
authors = []
license = "MIT"

[profile.release]
ldflags = "-s -w"
tags = []
gcflags = ""
output = "bin/app"


[tasks]
list = "rig run --list"
help = "rig --help"
build = "go build ./..."
test = "go test ./..."
vet = "go vet ./..."
fmt = "gofmt -s -w ."
run = "go run ."

[tools]
